[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
aes-gcm = "0.10"
sha2 = "0.10"
rand = "0.8"
rpassword = "7"
dirs = "5"